[project]
name = 'LuxuryGoods'
description = ''
authors = []
telemetry = true
cache_dir = '.cache'
requirements = []
[contracts.LuxurryNFt]
path = 'contracts/LuxurryNFt.clar'
clarity_version = 2
epoch = 2.5

[contracts.nftApprovable-trait]
path = 'contracts/nftApprovable-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.nftTrait]
path = 'contracts/nftTrait.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
